run_type = "staged_learning"
device = "cuda:0"
tb_logdir = "tb_stage1"
json_out_config = "_stage1.json"

[parameters]
prior_file = "priors/reinvent.prior"
agent_file = "priors/reinvent.prior"
summary_csv_prefix = "stage1"
batch_size = 100
use_checkpoint = false

[learning_strategy]
type = "dap"
sigma = 128
rate = 0.0001

[[stage]]
max_score = 1.0
max_steps = 300
chkpt_file = "stage1.chkpt"

[stage.scoring]
type = "geometric_mean"

[[stage.scoring.component]]
[stage.scoring.component.druglike]
[[stage.scoring.component.druglike.endpoint]]
name = "Druglike"
weight = 0.5

[[stage.scoring.component]]
[stage.scoring.component.diversity]
[[stage.scoring.component.diversity.endpoint]]
name = "Diversity"
weight = 0.5